# Site settings
title: {My Coding Life}
header-img: img/home-bg.png
email: michellereyes09@gmail.com
copyright_name: micrey015
description: > # this means to ignore newlines until "baseurl:"
  My journey to be a developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  micrey015
learn_profile: micrey015
email_username: michellereyes09@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
